apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: managed-server-secret
    type: Opaque
    stringData:
      openshiftToken: {{ .Values.backend.openshift.token }}
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: managed-server-ui-backend
      labels:
        app: managed-server-ui-backend
    spec:
      lookupPolicy:
        local: true
      tags:
        - from:
            kind: DockerImage
            name: {{ .Values.backend.image }}
          generation: null
          importPolicy: { }
          name: latest
          referencePolicy:
            type: ""
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: managed-server-ui-backend
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: managed-server-ui-backend
      template:
        metadata:
          labels:
            app: managed-server-ui-backend
        spec:
          containers:
            - name: managed-server-ui-backend
              image: managed-server-ui-backend
              imagePullPolicy: Always
              ports:
                - name: jolokia
                  containerPort: 8778
                  protocol: TCP
                - name: http
                  containerPort: 8080
                  protocol: TCP
                - name: ping
                  containerPort: 8888
                  protocol: TCP
                - name: admin
                  containerPort: 9990
                  protocol: TCP
                - name: https
                  containerPort: 8443
                  protocol: TCP
              envFrom:
                - prefix: postgresql-secret-
                  secretRef:
                    name: {{ .Values.backend.database.secretName }}
                - prefix: managed-server-secret-
                  secretRef:
                    name: managed-server-secret
              env:
                - name: QUARKUS_DATASOURCE_JDBC_URL
                  value: jdbc:postgresql://${POSTGRESQL_SERVICE_HOST}:${POSTGRESQL_SERVICE_PORT_POSTGRESQL}/${postgresql-secret-database-name}
                - name: QUARKUS_DATASOURCE_USERNAME
                  value: ${postgresql-secret-database-user}
                - name: QUARKUS_DATASOURCE_PASSWORD
                  value: ${postgresql-secret-database-password}
                  # Eventually this should be a persistent volume mount
                - name: MANAGED_SERVER_UI_BACKEND_WORKDIR
                  value: "/tmp/managed-server"
                # TODO: We don't know these - make the user create a Helm chart with them filled in?
                - name: MANAGED_SERVER_OPENSHIFT_SERVER
                  value: {{ .Values.backend.openshift.server }}
                - name: MANAGED_SERVER_OPENSHIFT_TOKEN
                  value: ${managed-server-secret-openshiftToken}
                - name: MANAGED_SERVER_OPENSHIFT_PROJECT
                  value: {{ .Values.backend.openshift.project }}

  - apiVersion: v1
    kind: Service
    metadata:
      name: managed-server-ui-backend
      labels:
        app: managed-server-ui-backend
    spec:
      selector:
        app: managed-server-ui-backend
      ipFamilies:
        - IPv4
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
      internalTrafficPolicy: Cluster
      type: ClusterIP
      sessionAffinity: None
      ipFamilyPolicy: SingleStack

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: managed-server-ui-backend
      labels:
        app: managed-server-ui-backend
    spec:
      to:
        kind: Service
        name: managed-server-ui-backend
        weight: 100
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
